import { Inter } from "next/font/google";
import "../app/globals.css";
import Head from 'next/head'

import { default as React, Suspense, useEffect, useState } from 'react';

import Header from "../components/navigation/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }) {

    return (
        <div>
            <Head>
                <title>Castor</title>
                <meta property="og:image" content="/opengraph-image.png" />
                <meta name="twitter:image" content="/twitter-image.pn" />

            </Head>
            <div className={inter.className}>
                <Header />
                <Suspense fallback="Loading...">
                    <Component {...pageProps} />
                </Suspense>
            </div>
        </div>
    );
}
