import { Inter } from "next/font/google";
import "../app/globals.css";

import { default as React, Suspense, useEffect, useState } from 'react';

import Header from "../components/navigation/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function MyApp({ Component, pageProps }) {

    return (
        <div lang="en">
            <div className={inter.className}>
                <Header />
                <Suspense fallback="Loading...">
                <Component {...pageProps} />
                </Suspense>
            </div>
        </div>
    );
}

export default MyApp;